### PR TITLE
Tidy up NavBar

### PR DESCRIPTION
**Pull request by pandahacker**
Fix for issue #8

### CODE REVIEW

**Review by srijeet-biswas — COMMENTED** [review]
share a screenshot in the comment section please @pandahacker

**Comment by pandahacker** [comment]
image

**Comment by srijeet-biswas** [comment]
@pandahacker  we admire your contribution, but we are planning to change the 2nd header line to sticky, I may suggest you to make work on #11 . the reason would be clear, I would be updating the idea as commit in a few minutes . I hope you understand. Thanks for the suggestion. it was great though

**Comment by srijeet-biswas** [comment]
also I am attaching a link to help you with  conflicts 
>syncing your fork with original head (https://digitaldrummerj.me/git-syncing-fork-with-original-repo/)

**Comment by srijeet-biswas** [comment]
just resolve #11 and open a PR for me to merge 👍

**Pull request closed without merging**
